<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="13" passed="9" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Testing log in functionality using valid credentials]]>
    </line>
  </reporter-output>
  <suite started-at="2020-01-12T11:29:51 EST" name="Test suite" finished-at="2020-01-12T11:29:54 EST" duration-ms="3241">
    <groups>
      <group name="regression">
        <method signature="TestTags.divide()[pri:0, instance:io.techleadacademy.testNGJan1120.TestTags@2e3fc542]" name="divide" class="io.techleadacademy.testNGJan1120.TestTags"/>
        <method signature="TestTags.subtract()[pri:-2, instance:io.techleadacademy.testNGJan1120.TestTags@2e3fc542]" name="subtract" class="io.techleadacademy.testNGJan1120.TestTags"/>
      </group> <!-- regression -->
      <group name="smoke">
        <method signature="TestTags.subtract()[pri:-2, instance:io.techleadacademy.testNGJan1120.TestTags@2e3fc542]" name="subtract" class="io.techleadacademy.testNGJan1120.TestTags"/>
        <method signature="TestTags.subtract2()[pri:-1, instance:io.techleadacademy.testNGJan1120.TestTags@2e3fc542]" name="subtract2" class="io.techleadacademy.testNGJan1120.TestTags"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2020-01-12T11:29:51 EST" name="Test 1" finished-at="2020-01-12T11:29:54 EST" duration-ms="3241">
      <class name="io.techleadacademy.testNGJan1120.TestTags">
        <test-method signature="subtract()[pri:-2, instance:io.techleadacademy.testNGJan1120.TestTags@2e3fc542]" started-at="2020-01-12T11:29:51 EST" name="subtract" finished-at="2020-01-12T11:29:51 EST" duration-ms="17" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- subtract -->
        <test-method signature="subtract2()[pri:-1, instance:io.techleadacademy.testNGJan1120.TestTags@2e3fc542]" started-at="2020-01-12T11:29:51 EST" name="subtract2" finished-at="2020-01-12T11:29:51 EST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- subtract2 -->
        <test-method signature="_001multiply()[pri:0, instance:io.techleadacademy.testNGJan1120.TestTags@2e3fc542]" started-at="2020-01-12T11:29:51 EST" name="_001multiply" finished-at="2020-01-12T11:29:51 EST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- _001multiply -->
        <test-method signature="add1(java.lang.reflect.Method)[pri:0, instance:io.techleadacademy.testNGJan1120.TestTags@2e3fc542]" started-at="2020-01-12T11:29:51 EST" name="add1" description="Adding positive numbers" finished-at="2020-01-12T11:29:51 EST" duration-ms="5" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void io.techleadacademy.testNGJan1120.TestTags.add1(java.lang.reflect.Method)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add1 -->
        <test-method signature="add2()[pri:0, instance:io.techleadacademy.testNGJan1120.TestTags@2e3fc542]" started-at="2020-01-12T11:29:51 EST" name="add2" finished-at="2020-01-12T11:29:51 EST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add2 -->
        <test-method signature="divide()[pri:0, instance:io.techleadacademy.testNGJan1120.TestTags@2e3fc542]" started-at="2020-01-12T11:29:51 EST" name="divide" finished-at="2020-01-12T11:29:51 EST" duration-ms="2" status="PASS">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at io.techleadacademy.testNGJan1120.TestTags.divide(TestTags.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divide -->
        <test-method signature="divide2()[pri:0, instance:io.techleadacademy.testNGJan1120.TestTags@2e3fc542]" started-at="2020-01-12T11:29:51 EST" name="divide2" finished-at="2020-01-12T11:29:51 EST" duration-ms="2" status="PASS">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at io.techleadacademy.testNGJan1120.TestTags.divide2(TestTags.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divide2 -->
        <test-method signature="logInPerformanceTest()[pri:0, instance:io.techleadacademy.testNGJan1120.TestTags@2e3fc542]" started-at="2020-01-12T11:29:51 EST" name="logInPerformanceTest" finished-at="2020-01-12T11:29:54 EST" duration-ms="3029" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logInPerformanceTest -->
        <test-method signature="testUserName(java.lang.String, java.lang.String)[pri:0, instance:io.techleadacademy.testNGJan1120.TestTags@2e3fc542]" started-at="2020-01-12T11:29:54 EST" name="testUserName" finished-at="2020-01-12T11:29:54 EST" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Parameter 'username' is required by @Test on method testUserName but has not been marked @Optional or defined
in /Users/admin/IdeaProjects/MavenProject/testNG.xml]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Parameter 'username' is required by @Test on method testUserName but has not been marked @Optional or defined
in /Users/admin/IdeaProjects/MavenProject/testNG.xml
at org.testng.internal.Parameters.createParams(Parameters.java:272)
at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:360)
at org.testng.internal.Parameters.createParameters(Parameters.java:704)
at org.testng.internal.Parameters.handleParameters(Parameters.java:879)
at org.testng.internal.Parameters.handleParameters(Parameters.java:744)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:783)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUserName -->
        <test-method signature="testUserName1(java.lang.String, java.lang.String)[pri:0, instance:io.techleadacademy.testNGJan1120.TestTags@2e3fc542]" started-at="2020-01-12T11:29:54 EST" name="testUserName1" finished-at="2020-01-12T11:29:54 EST" duration-ms="7" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[XxX]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[abcdef]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [XxX] but found [Your name]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [XxX] but found [Your name]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at io.techleadacademy.testNGJan1120.TestTags.testUserName1(TestTags.java:91)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Testing log in functionality using valid credentials]]>
            </line>
          </reporter-output>
        </test-method> <!-- testUserName1 -->
      </class> <!-- io.techleadacademy.testNGJan1120.TestTags -->
      <class name="io.techleadacademy.TestingTestNG">
        <test-method signature="testTwoNums()[pri:0, instance:io.techleadacademy.TestingTestNG@150c158]" started-at="2020-01-12T11:29:54 EST" name="testTwoNums" finished-at="2020-01-12T11:29:54 EST" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTwoNums -->
      </class> <!-- io.techleadacademy.TestingTestNG -->
    </test> <!-- Test 1 -->
  </suite> <!-- Test suite -->
</testng-results>
